package exceptions.testthrows;

public class Main {
	public static void main(String[] args) {
		try{
			A.f1();
		}catch(Exception e){
			System.out.println("Exception of type: "+e+" has been caught.");
		}
		
	}
}
