package exceptions.testthrows;

public class Main {
	public static void main(String[] args) {
		A.f1();
		
	}
}
